# Generated by Django 3.2.4 on 2021-06-22 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctg', models.CharField(max_length=1)),
                ('rollno', models.CharField(max_length=9)),
                ('regno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('fname', models.CharField(max_length=40)),
                ('dob', models.CharField(max_length=8)),
                ('fl', models.CharField(max_length=3)),
                ('sl', models.CharField(max_length=3)),
                ('addl', models.CharField(max_length=3)),
                ('subj', models.CharField(blank=True, max_length=40, null=True)),
                ('fl_marks', models.CharField(max_length=3)),
                ('sl_marks', models.CharField(max_length=3)),
                ('maths_marks', models.CharField(max_length=3)),
                ('psc_marks', models.CharField(max_length=3)),
                ('lst_marks', models.CharField(max_length=3)),
                ('hist_marks', models.CharField(max_length=3)),
                ('geog_marks', models.CharField(max_length=3)),
                ('opt1_marks', models.CharField(max_length=3)),
                ('opt2_marks', models.CharField(max_length=3)),
                ('opt3_marks', models.CharField(max_length=3)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students HM',
            },
        ),
        migrations.CreateModel(
            name='StudentAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctg', models.CharField(max_length=1)),
                ('rollno', models.CharField(max_length=9)),
                ('regno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('fname', models.CharField(max_length=40)),
                ('dob', models.CharField(max_length=8)),
                ('fl', models.CharField(max_length=3)),
                ('sl', models.CharField(max_length=3)),
                ('addl', models.CharField(max_length=3)),
                ('subj', models.CharField(blank=True, max_length=40, null=True)),
                ('fl_marks', models.CharField(max_length=3)),
                ('sl_marks', models.CharField(max_length=3)),
                ('maths_marks', models.CharField(max_length=3)),
                ('arabic_marks', models.CharField(max_length=3)),
                ('hadith_marks', models.CharField(max_length=3)),
                ('tafsir_marks', models.CharField(max_length=3)),
                ('fiqh_marks', models.CharField(max_length=2)),
                ('psc_marks', models.CharField(max_length=2)),
                ('lst_marks', models.CharField(max_length=2)),
                ('hist_marks', models.CharField(max_length=3)),
                ('geog_marks', models.CharField(max_length=2)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students AL',
            },
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
