# Generated by Django 3.2.4 on 2021-06-24 11:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mdmarks.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctg', models.CharField(max_length=2)),
                ('rollno', models.CharField(max_length=9, verbose_name='Roll-Number')),
                ('regno', models.CharField(max_length=10, verbose_name='Registration Number')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('fname', models.CharField(max_length=40, verbose_name="Father's Name")),
                ('dob', models.CharField(max_length=8, verbose_name='Date of Birth')),
                ('subj', models.CharField(max_length=40, null=True, verbose_name='Subject Combination')),
                ('fl', models.CharField(max_length=3)),
                ('sl', models.CharField(max_length=3, null=True)),
                ('fl_marks', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks])),
                ('english_marks', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks], verbose_name='English')),
                ('maths_marks', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks], verbose_name='Mathematics')),
                ('arabic_marks', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks], verbose_name='Arabic')),
                ('hist_marks', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks], verbose_name='History')),
                ('opt_marks', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks])),
                ('complete', models.BooleanField(default=False)),
                ('islam_parichay', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks])),
                ('psc_marks', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks], verbose_name='Physical Science')),
                ('lsc_marks', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks], verbose_name='Life Science')),
                ('geog_marks', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks], verbose_name='Geography')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students HM',
            },
        ),
        migrations.CreateModel(
            name='StudentAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctg', models.CharField(max_length=2)),
                ('rollno', models.CharField(max_length=9, verbose_name='Roll-Number')),
                ('regno', models.CharField(max_length=10, verbose_name='Registration Number')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('fname', models.CharField(max_length=40, verbose_name="Father's Name")),
                ('dob', models.CharField(max_length=8, verbose_name='Date of Birth')),
                ('subj', models.CharField(max_length=40, null=True, verbose_name='Subject Combination')),
                ('fl', models.CharField(max_length=3)),
                ('sl', models.CharField(max_length=3, null=True)),
                ('fl_marks', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks])),
                ('english_marks', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks], verbose_name='English')),
                ('maths_marks', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks], verbose_name='Mathematics')),
                ('arabic_marks', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks], verbose_name='Arabic')),
                ('hist_marks', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks], verbose_name='History')),
                ('opt_marks', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks])),
                ('complete', models.BooleanField(default=False)),
                ('psc_marks', models.CharField(max_length=2, null=True, validators=[mdmarks.validators.validate_50_marks], verbose_name='Physical Science')),
                ('lsc_marks', models.CharField(max_length=2, null=True, validators=[mdmarks.validators.validate_50_marks], verbose_name='Life Science')),
                ('geog_marks', models.CharField(max_length=2, null=True, validators=[mdmarks.validators.validate_50_marks], verbose_name='Geography')),
                ('hadith', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks])),
                ('tafsir', models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_100_marks])),
                ('fiqh', models.CharField(max_length=2, null=True, validators=[mdmarks.validators.validate_50_marks])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students AL',
            },
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
