# Generated by Django 3.2.4 on 2021-06-23 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdmarks', '0003_auto_20210622_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studental',
            old_name='lst_marks',
            new_name='lsc_marks',
        ),
        migrations.RenameField(
            model_name='studenthm',
            old_name='opt1_marks',
            new_name='arabic_marks',
        ),
        migrations.RenameField(
            model_name='studenthm',
            old_name='opt2_marks',
            new_name='islam_parichay_marks',
        ),
        migrations.RenameField(
            model_name='studenthm',
            old_name='opt3_marks',
            new_name='opt_marks',
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='phone',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
