# Generated by Django 3.2.4 on 2021-06-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdmarks', '0005_auto_20210623_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studental',
            old_name='arabic_marks',
            new_name='arabic',
        ),
        migrations.RenameField(
            model_name='studental',
            old_name='fiqh_marks',
            new_name='fiqh',
        ),
        migrations.RenameField(
            model_name='studental',
            old_name='geog_marks',
            new_name='geog',
        ),
        migrations.RenameField(
            model_name='studental',
            old_name='fl_marks',
            new_name='hadith',
        ),
        migrations.RenameField(
            model_name='studental',
            old_name='hadith_marks',
            new_name='hist',
        ),
        migrations.RenameField(
            model_name='studental',
            old_name='lsc_marks',
            new_name='lsc',
        ),
        migrations.RenameField(
            model_name='studental',
            old_name='hist_marks',
            new_name='maths',
        ),
        migrations.RenameField(
            model_name='studental',
            old_name='psc_marks',
            new_name='psc',
        ),
        migrations.RenameField(
            model_name='studental',
            old_name='maths_marks',
            new_name='tafsir',
        ),
        migrations.RenameField(
            model_name='studenthm',
            old_name='arabic_marks',
            new_name='arabic',
        ),
        migrations.RenameField(
            model_name='studenthm',
            old_name='fl_marks',
            new_name='geog',
        ),
        migrations.RenameField(
            model_name='studenthm',
            old_name='geog_marks',
            new_name='hist',
        ),
        migrations.RenameField(
            model_name='studenthm',
            old_name='hist_marks',
            new_name='islam_parichay',
        ),
        migrations.RenameField(
            model_name='studenthm',
            old_name='islam_parichay_marks',
            new_name='lst',
        ),
        migrations.RenameField(
            model_name='studenthm',
            old_name='lst_marks',
            new_name='maths',
        ),
        migrations.RenameField(
            model_name='studenthm',
            old_name='maths_marks',
            new_name='opt',
        ),
        migrations.RenameField(
            model_name='studenthm',
            old_name='opt_marks',
            new_name='psc',
        ),
        migrations.RemoveField(
            model_name='studental',
            name='sl_marks',
        ),
        migrations.RemoveField(
            model_name='studental',
            name='tafsir_marks',
        ),
        migrations.RemoveField(
            model_name='studenthm',
            name='psc_marks',
        ),
        migrations.RemoveField(
            model_name='studenthm',
            name='sl_marks',
        ),
        migrations.AlterField(
            model_name='studental',
            name='fl',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='fl',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
