# Generated by Django 3.2.4 on 2021-06-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdmarks', '0006_auto_20210623_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='studental',
            name='opt',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='opt',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
