# Generated by Django 3.2.4 on 2021-06-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdmarks', '0007_auto_20210623_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studental',
            old_name='maths',
            new_name='english_marks',
        ),
        migrations.RenameField(
            model_name='studenthm',
            old_name='maths',
            new_name='english_marks',
        ),
        migrations.AddField(
            model_name='studental',
            name='fl_marks',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='studental',
            name='maths_marks',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='studenthm',
            name='fl_marks',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='studenthm',
            name='maths_marks',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='studental',
            name='fl',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='fl',
            field=models.CharField(max_length=3),
        ),
    ]
