# Generated by Django 3.2.4 on 2021-06-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdmarks', '0008_auto_20210623_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenthm',
            old_name='opt',
            new_name='opt_marks',
        ),
        migrations.RemoveField(
            model_name='studental',
            name='opt',
        ),
        migrations.AddField(
            model_name='studental',
            name='opt_marks',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='studental',
            name='subj',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='subj',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
