# Generated by Django 3.2.4 on 2021-06-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdmarks', '0009_auto_20210624_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studental',
            name='sl',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='sl',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
