# Generated by Django 3.2.4 on 2021-06-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdmarks', '0010_auto_20210624_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthm',
            name='lst',
        ),
        migrations.AddField(
            model_name='studenthm',
            name='lsc',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studental',
            name='english_marks',
            field=models.CharField(max_length=3, null=True, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='studental',
            name='maths_marks',
            field=models.CharField(max_length=3, null=True, verbose_name='Mathematics'),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='english_marks',
            field=models.CharField(max_length=3, null=True, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='geog',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='maths_marks',
            field=models.CharField(max_length=3, null=True, verbose_name='Mathematics'),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='psc',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
