# Generated by Django 3.2.4 on 2021-06-23 22:09

from django.db import migrations, models
import mdmarks.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mdmarks', '0013_auto_20210624_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studental',
            name='arabic_marks',
            field=models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_marks], verbose_name='Arabic'),
        ),
        migrations.AlterField(
            model_name='studental',
            name='dob',
            field=models.CharField(max_length=8, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='studental',
            name='english_marks',
            field=models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_marks], verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='studental',
            name='fiqh',
            field=models.CharField(max_length=2, null=True, validators=[mdmarks.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='studental',
            name='fl_marks',
            field=models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='studental',
            name='fname',
            field=models.CharField(max_length=40, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='studental',
            name='geog_marks',
            field=models.CharField(max_length=2, null=True, validators=[mdmarks.validators.validate_marks], verbose_name='Geography'),
        ),
        migrations.AlterField(
            model_name='studental',
            name='hadith',
            field=models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='studental',
            name='hist_marks',
            field=models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_marks], verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='studental',
            name='lsc_marks',
            field=models.CharField(max_length=2, null=True, validators=[mdmarks.validators.validate_marks], verbose_name='Life Science'),
        ),
        migrations.AlterField(
            model_name='studental',
            name='maths_marks',
            field=models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_marks], verbose_name='Mathematics'),
        ),
        migrations.AlterField(
            model_name='studental',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='studental',
            name='opt_marks',
            field=models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='studental',
            name='psc_marks',
            field=models.CharField(max_length=2, null=True, validators=[mdmarks.validators.validate_marks], verbose_name='Physical Science'),
        ),
        migrations.AlterField(
            model_name='studental',
            name='regno',
            field=models.CharField(max_length=10, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='studental',
            name='rollno',
            field=models.CharField(max_length=9, verbose_name='Roll-Number'),
        ),
        migrations.AlterField(
            model_name='studental',
            name='subj',
            field=models.CharField(max_length=40, null=True, verbose_name='Subject Combination'),
        ),
        migrations.AlterField(
            model_name='studental',
            name='tafsir',
            field=models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='arabic_marks',
            field=models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_marks], verbose_name='Arabic'),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='dob',
            field=models.CharField(max_length=8, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='english_marks',
            field=models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_marks], verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='fl_marks',
            field=models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='fname',
            field=models.CharField(max_length=40, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='geog_marks',
            field=models.CharField(max_length=2, null=True, validators=[mdmarks.validators.validate_marks], verbose_name='Geography'),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='hist_marks',
            field=models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_marks], verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='islam_parichay',
            field=models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='lsc_marks',
            field=models.CharField(max_length=2, null=True, validators=[mdmarks.validators.validate_marks], verbose_name='Life Science'),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='maths_marks',
            field=models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_marks], verbose_name='Mathematics'),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='opt_marks',
            field=models.CharField(max_length=3, null=True, validators=[mdmarks.validators.validate_marks]),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='psc_marks',
            field=models.CharField(max_length=2, null=True, validators=[mdmarks.validators.validate_marks], verbose_name='Physical Science'),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='regno',
            field=models.CharField(max_length=10, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='rollno',
            field=models.CharField(max_length=9, verbose_name='Roll-Number'),
        ),
        migrations.AlterField(
            model_name='studenthm',
            name='subj',
            field=models.CharField(max_length=40, null=True, verbose_name='Subject Combination'),
        ),
    ]
